---
- name: Basic Installation
  hosts: all
  become: true
  vars:
    repo_url: "https://github.com/nadaved1/hailo-apps-internal.git"
    repo_dest: "/tmp/hailo-apps-internal"
    branch: "main"
    test_arg: ""

  pre_tasks:
    - name: Verify effective user (should be 0)
      command: id -u
      register: idu
      changed_when: false

    - name: Debug user
      debug:
        msg: "Effective UID: {{ idu.stdout }}"

  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update & upgrade packages (RedHat)
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Remove unneeded packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Install dependencies
      package:
        name:
          - curl
          - hailo-all
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Clone the hailo-apps-internal repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        force: yes

    - name: Run installation script
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        ./install.sh
      args:
        executable: /bin/bash

    - name: Run tests
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        source venv_hailo_apps/bin/activate
        ./run_tests.sh {{ test_arg }}
      args:
        executable: /bin/bash
