---
- name: Basic Installation
  hosts: all
  become: true

  vars:
    repo_url: "https://github.com/nadaved1/hailo-apps-internal.git"
    repo_dest: "/tmp/hailo-apps-internal"
    branch: "main"
    test_arg: ""

    run_user: "{{ ansible_user | default('semaphore') }}"
    run_group: "{{ ansible_user | default('semaphore') }}"

  pre_tasks:
    - name: Verify effective user (should be 0)
      command: id -u
      register: idu
      changed_when: false

    - name: Debug user
      debug:
        msg: "Effective UID: {{ idu.stdout }}"

  tasks:
    # ---------------------
    # System Dependencies
    # ---------------------
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update & upgrade packages (RedHat)
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Remove unneeded packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Install dependencies
      package:
        name:
          - curl
          - hailo-all
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    # ---------------------
    # Clone as run_user
    # ---------------------
    - name: Clone the hailo-apps-internal repo as run_user
      become: true
      become_user: "{{ run_user }}"
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        force: yes

    # ---------------------
    # Ensure ownership
    # ---------------------
    - name: Ensure repo directory ownership is correct
      become: true
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        owner: "{{ run_user }}"
        group: "{{ run_group }}"
        recurse: true
        state: directory

    # ---------------------
    # Install script
    # ---------------------
    - name: Run installation script as run_user
      become: true
      become_user: "{{ run_user }}"
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        ./install.sh
      args:
        executable: /bin/bash

    # ---------------------
    # Run tests
    # ---------------------
    - name: Run tests as run_user
      become: true
      become_user: "{{ run_user }}"
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        source venv_hailo_apps/bin/activate
        ./run_tests.sh --pipelines
      args:
        executable: /bin/bash
