---
- name: Basic Installation
  hosts: all
  become: true

  vars:
    # ---------------------
    # Repo settings
    # ---------------------
    repo_url: "https://github.com/hailocs/hailo-apps-internal.git"
    repo_dest: "/tmp/hailo-apps-internal"
    branch: "main"

    # ---------------------
    # Test selection from Semaphore:
    #
    # Options:
    #   sanity
    #   install
    #   pipelines
    #   full    (default → run all tests)
    # ---------------------
    test_type: "full"

    # The user that will own all files & run install/tests
    run_user: "{{ ansible_user | default('semaphore') }}"
    run_group: "{{ ansible_user | default('semaphore') }}"

  pre_tasks:
    # Verify we're running as root (Ansible's become)
    - name: Verify effective user (should be 0)
      ansible.builtin.command: id -u
      register: idu
      changed_when: false

    - name: Debug user
      ansible.builtin.debug:
        msg: "Effective UID: {{ idu.stdout }}"

    # Ensure test_type is valid
    - name: Validate test_type
      ansible.builtin.assert:
        that:
          - test_type in ['sanity', 'install', 'full', 'pipelines']
        fail_msg: "Invalid test_type '{{ test_type }}'. Use sanity | install | full | pipelines."

    # Map UI test_type → script flags
    - name: Map test_type to script flag
      ansible.builtin.set_fact:
        test_flag: >-
          {% if test_type == 'sanity' %}--sanity
          {% elif test_type == 'install' %}--install
          {% elif test_type == 'pipelines' %}--pipelines
          {% else %}{% endif %}

  tasks:
    # ---------------------
    # System Dependencies
    # ---------------------
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Remove unneeded packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Install dependencies
      ansible.builtin.package:
        name:
          - curl
          - hailo-all
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    # ---------------------
    # Clone repo as real user
    # ---------------------
    - name: Clone hailo-apps-internal as run_user
      become_user: "{{ run_user }}"
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        force: yes

    - name: Ensure repo directory ownership is correct
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        owner: "{{ run_user }}"
        group: "{{ run_group }}"
        recurse: true
        state: directory

    # ---------------------
    # Install hailo-apps
    # ---------------------
    - name: Run installation script as run_user
      become_user: "{{ run_user }}"
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        ./install.sh
      args:
        executable: /bin/bash

    # ---------------------
    # Run tests
    # ---------------------
    - name: Run tests as run_user
      become_user: "{{ run_user }}"
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        source venv_hailo_apps/bin/activate
        ./run_tests.sh{{ " " + test_flag if test_flag | length > 0 else "" }}
      args:
        executable: /bin/bash
