---
- name: Basic Installation
  hosts: all
  become: true

  vars:
    base_url: "https://dev-public.hailo.ai/2025_10/Hailo8"
    download_path: "/tmp/hailo_pkgs"

    hrt_ver: "4.23.0"
    tappas_ver: "5.1.0"

    repo_url: "https://github.com/hailocs/hailo-apps-internal.git"
    repo_dest: "/tmp/hailo-apps-internal"
    branch: "main"
    test_arg: ""

    hailo_wheels:
      "3.10": "hailort-{{ hrt_ver }}-cp310-cp310-linux_x86_64.whl"
      "3.11": "hailort-{{ hrt_ver }}-cp311-cp311-linux_x86_64.whl"
      "3.12": "hailort-{{ hrt_ver }}-cp312-cp312-linux_x86_64.whl"
      "3.13": "hailort-{{ hrt_ver }}-cp313-cp313-linux_x86_64.whl"

  pre_tasks:

    - name: Register kernel version
      ansible.builtin.command: uname -r
      register: kernel_ver
      changed_when: false

    - name: Register OS version
      ansible.builtin.shell: "grep VERSION /etc/os-release"
      register: os_ver
      changed_when: false

    - name: Register uptime
      ansible.builtin.command: uptime
      register: uptime_out
      changed_when: false

    - name: Gather Python facts
      setup:
        filter: "ansible_python"

    - name: Set Python version variable
      set_fact:
        py_ver: "{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

    - name: Determine correct wheel file
      set_fact:
        target_whl: "{{ hailo_wheels[py_ver] | default(None) }}"
      failed_when: target_whl is none
      vars:
        ansible_facts: "{{ ansible_facts }}"

    - name: Summary of system info
      debug:
        msg:
          - "Kernel: {{ kernel_ver.stdout }}"
          - "Python: {{ py_ver }}"
          - "OS version line: {{ os_ver.stdout }}"
          - "Uptime: {{ uptime_out.stdout }}"

  tasks:

    # --------------------------------------------------
    # OS Upgrades / Updates
    # --------------------------------------------------

    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update & upgrade packages (RedHat)
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Remove unneeded packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    # --------------------------------------------------
    # Dependencies
    # --------------------------------------------------

    - name: Install dependencies
      package:
        name:
          - curl
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Ensure temp download directory exists
      file:
        path: "{{ download_path }}"
        state: directory
        mode: '0755'

    # --------------------------------------------------
    # Download & Install Hailo Packages
    # --------------------------------------------------

    - name: Download Hailo deb and wheel files
      get_url:
        url: "{{ base_url }}/{{ item }}"
        dest: "{{ download_path }}/{{ item }}"
      loop:
        - "{{ target_whl }}"
        - "hailort_{{ hrt_ver }}_amd64.deb"
        - "hailo-tappas-core_{{ tappas_ver }}_amd64.deb"
        - "hailort-pcie-driver_{{ hrt_ver }}_all.deb"

    - name: Install .deb packages
      apt:
        deb: "{{ download_path }}/{{ item }}"
        state: present
      loop:
        - "hailort-pcie-driver_{{ hrt_ver }}_all.deb"
        - "hailort_{{ hrt_ver }}_amd64.deb"
        - "hailo-tappas-core_{{ tappas_ver }}_amd64.deb"
      when: ansible_os_family == "Debian"

    - name: Install Python wheel
      pip:
        name: "{{ download_path }}/{{ target_whl }}"
        state: present
        executable: pip3

    # --------------------------------------------------
    # Clone + Install hailo-apps-internal
    # --------------------------------------------------

    - name: Clone hailo-apps-internal
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        force: yes

    - name: Run install.sh
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        ./install.sh
      args:
        executable: /bin/bash

    # --------------------------------------------------
    # Tests
    # --------------------------------------------------

    - name: Run sanity tests
      ansible.builtin.shell: |
        cd {{ repo_dest }}
        source venv_hailo_apps/bin/activate
        ./run_tests.sh {{ test_arg }}
      args:
        executable: /bin/bash
