- name: Hailo-8 x86 Installation & Test Runner
  hosts: all
  become: true

  vars:

    # ---------------------
    # Resource downloading control
    # Options:
    #   - true  (default)
    #   - false (adds --no-download)
    # ---------------------
    download_resources: true

    # ---------------------
    # Repo settings
    # ---------------------
    repo_url: "https://github.com/hailocs/hailo-apps-internal.git"
    repo_dest: "/tmp/hailo-apps-internal"
    branch: "main"
    venv_path: "{{ repo_dest }}/venv_hailo_apps"

    # ---------------------
    # Test selection
    # ---------------------
    test_type: ""

    # ---------------------
    # Resource URLs / versions
    # ---------------------
    base_url: "https://dev-public.hailo.ai/2025_10/Hailo8"
    download_path: "/tmp/hailo_pkgs"

    hrt_ver: "4.23.0"
    tappas_ver: "5.1.0"

    hailo_wheels:
      "3.10": "hailort-{{ hrt_ver }}-cp310-cp310-linux_x86_64.whl"
      "3.11": "hailort-{{ hrt_ver }}-cp311-cp311-linux_x86_64.whl"
      "3.12": "hailort-{{ hrt_ver }}-cp312-cp312-linux_x86_64.whl"
      "3.13": "hailort-{{ hrt_ver }}-cp313-cp313-linux_x86_64.whl"

    # Map Ubuntu major version → tappas suffix
    tappas_suffix_map:
      "22": "ub22"
      "24": "ub24"

  pre_tasks:

    # ---------------------------------------------------
    # Diagnostics
    # ---------------------------------------------------
    - name: Register kernel version
      ansible.builtin.command: uname -r
      register: kernel_ver
      changed_when: false

    - name: Register OS version
      ansible.builtin.shell: "grep VERSION /etc/os-release"
      register: os_ver
      changed_when: false

    - name: Register uptime
      ansible.builtin.command: uptime
      register: uptime_out
      changed_when: false

    - name: Gather Python facts
      setup:
        filter: "ansible_python"

    - name: Set Python version variable
      ansible.builtin.set_fact:
        py_ver: "{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

    # ---------------------------------------------------
    # Determine wheel file
    # ---------------------------------------------------
    - name: Determine correct wheel file
      ansible.builtin.set_fact:
        target_whl: "{{ hailo_wheels[py_ver] | default(None) }}"
      failed_when: target_whl is none

    # ---------------------------------------------------
    # Determine tappas-core package name (Ubuntu only)
    # ---------------------------------------------------
    - name: Determine tappas-core suffix for Ubuntu
      ansible.builtin.set_fact:
        tappas_suffix: "{{ tappas_suffix_map[ansible_distribution_major_version] | default(None) }}"
      when: ansible_distribution == "Ubuntu"

    - name: Fail if Ubuntu version is unsupported for tappas-core
      ansible.builtin.fail:
        msg: >-
          Unsupported Ubuntu major version '{{ ansible_distribution_major_version }}' for tappas-core.
          Supported: {{ tappas_suffix_map.keys() | list }}.
      when:
        - ansible_distribution == "Ubuntu"
        - tappas_suffix is not defined or tappas_suffix is none

    - name: Build tappas-core filename on Ubuntu
      ansible.builtin.set_fact:
        tappas_core_pkg: "hailo-tappas-core_{{ tappas_ver }}_amd64_{{ tappas_suffix }}.deb"
      when: ansible_distribution == "Ubuntu"

    # ---------------------------------------------------
    # Map download_resources → CLI flag
    # ---------------------------------------------------
    - name: Map download_resources to flag
      ansible.builtin.set_fact:
        download_flag: "{% if not download_resources %}--no-download{% else %}{% endif %}"

    # ---------------------------------------------------
    # System summary
    # ---------------------------------------------------
    - name: Summary of system info
      ansible.builtin.debug:
        msg:
          - "Kernel: {{ kernel_ver.stdout }}"
          - "Python: {{ py_ver }}"
          - "OS: {{ os_ver.stdout }}"
          - "Uptime: {{ uptime_out.stdout }}"
          - "Download resources: {{ download_resources }}"
          - "Download flag: '{{ download_flag }}'"
          - "Target wheel: {{ target_whl }}"
          - "tappas-core pkg (Ubuntu only): {{ tappas_core_pkg | default('N/A') }}"

  tasks:

    # ---------------------------------------------------
    # System dependencies
    # ---------------------------------------------------
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update & upgrade packages (RedHat)
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Remove unneeded packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Install dependencies
      ansible.builtin.package:
        name:
          - curl
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Ensure temp download directory exists
      ansible.builtin.file:
        path: "{{ download_path }}"
        state: directory
        mode: '0755'

    # ---------------------------------------------------
    # Download Hailo deb and wheel files
    # ---------------------------------------------------
    - name: Download Hailo wheel (Python)
      ansible.builtin.get_url:
        url: "{{ base_url }}/{{ target_whl }}"
        dest: "{{ download_path }}/{{ target_whl }}"

    - name: Download Hailo PCIe driver (.deb)
      ansible.builtin.get_url:
        url: "{{ base_url }}/hailort-pcie-driver_{{ hrt_ver }}_all.deb"
        dest: "{{ download_path }}/hailort-pcie-driver_{{ hrt_ver }}_all.deb"
      when: ansible_os_family == "Debian"

    - name: Download Hailo runtime (.deb)
      ansible.builtin.get_url:
        url: "{{ base_url }}/hailort_{{ hrt_ver }}_amd64.deb"
        dest: "{{ download_path }}/hailort_{{ hrt_ver }}_amd64.deb"
      when: ansible_os_family == "Debian"

    - name: Download tappas-core (.deb) for Ubuntu
      ansible.builtin.get_url:
        url: "{{ base_url }}/{{ tappas_core_pkg }}"
        dest: "{{ download_path }}/{{ tappas_core_pkg }}"
      when: ansible_distribution == "Ubuntu"

    # ---------------------------------------------------
    # Install Hailo packages (Debian/Ubuntu)
    # ---------------------------------------------------
    - name: Install .deb packages (order matters)
      ansible.builtin.apt:
        deb: "{{ download_path }}/{{ item }}"
        state: present
      loop:
        - "hailort-pcie-driver_{{ hrt_ver }}_all.deb"
        - "hailort_{{ hrt_ver }}_amd64.deb"
        - "{{ tappas_core_pkg | default(omit) }}"
      when: ansible_os_family == "Debian"

    # ---------------------------------------------------
    # Clone + Install hailo-apps-internal (creates venv_hailo_apps)
    # ---------------------------------------------------
    - name: Clone hailo-apps-internal
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        force: yes

    - name: Run install.sh (creates {{ venv_path }})
      ansible.builtin.shell: |
        set -euo pipefail
        cd {{ repo_dest }}
        ./install.sh
      args:
        executable: /bin/bash

    # ---------------------------------------------------
    # Install Hailo Python wheel INSIDE the repo venv (PEP 668-safe)
    # ---------------------------------------------------
    - name: Ensure pip is up-to-date in repo venv
      ansible.builtin.pip:
        name:
          - pip
          - setuptools
          - wheel
        state: latest
        executable: "{{ venv_path }}/bin/pip"

    - name: Install Hailo wheel inside repo venv
      ansible.builtin.pip:
        name: "{{ download_path }}/{{ target_whl }}"
        state: present
        executable: "{{ venv_path }}/bin/pip"

    # ---------------------------------------------------
    # Run tests using the same venv
    # ---------------------------------------------------
    - name: Run tests (async)
      ansible.builtin.shell: |
        set -euo pipefail
        cd {{ repo_dest }}
        source "{{ venv_path }}/bin/activate"
        ./run_tests.sh {{ test_type }} {{ download_flag }}
      args:
        executable: /bin/bash
      async: 7200
      poll: 30